name: Daily Tech News Digest

on:
  schedule:
    - cron: "0 7 * * *"  # Runs daily at 07:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Crew agents
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY }}
          SENGRID_API_KEY: ${{secrets.SENGRID_API_KEY }}
          EMAIL_TO: ${{secrets.EMAIL_TO }}
          
        run: python send_email.py






